### ISSUE TITLE
Duplicate code for WSPR Desktop Transmitter

### ISSUE THREAD

**Issue by jj1bdx** [HarrydeBug/1011-WSPR-TX_LP1#1]
In 
https://github.com/HarrydeBug/1011-WSPR-TX_LP1/blob/51d9133f03640325860655f6f6b29d3b29eaed39/Standard%20Firmware/Beta/WSPR-TX0.90.ino#L329-L345
I see two if code blocks for the same product model value `Product_Model == 1012`, for the MidPlus and HighPlus model. In this code only the values for the HighPlus model become valid. Any fix for the MidPlus user?

**Comment by HarrydeBug** [comment]
This is a help for me to get initial factory values in to my different models.
When compiling for MidPlus I simply comment out the HighPlus section.
These are just initial values for Factory Setup and can be changed with the Factory Setup program.

**Comment by jj1bdx** [comment]
@HarrydeBug So the model number of MidPlus and HighPlus are the same?

**Comment by HarrydeBug** [comment]
Yes, correct.

Den ons 22 juli 2020 kl 13:14 skrev Kenji Rikitake <notifications@github.com
