### ISSUE TITLE
Encoding Altitude in Power Field - invalid powers used?

### ISSUE THREAD

**Issue by KevWal** [HarrydeBug/1011-WSPR-TX_LP1#3]
Hi Harry

Does your encoding of Altitude in the WSPR Power field not break the WSPR standard?

Power can only be one of 19 discrete values?  Where as you set any value between 0 and 60?

http://hojoham.blogspot.com/2016/05/wisp1-telemetry-revisited.html

Thanks very much
Kevin

**Comment by HarrydeBug** [comment]
Hi Kevin.
I don't set any value, I use the same 3dB steps as the WSPR standard use.

73
//Harry

**Comment by KevWal** [comment]
My apologies, 

I noted the version comment of "Added Altitude encoding in the power field option." and found the code:

'             GadgetData.WSPRData.TXPowerdBm = fix.altitude() / 300; //Max 18km altitude
             if (GadgetData.WSPRData.TXPowerdBm > 60 ) GadgetData.WSPRData.TXPowerdBm =60;
             if (GadgetData.WSPRData.TXPowerdBm < 0 ) GadgetData.WSPRData.TXPowerdBm =0;,

but omitted to follow that through where I would have seend the wspr_message_prep code:

'// If we got this far, we have an invalid power level, so we'll round down
  for(i = 1; i < 19; i++)
  {
    if(dbm < valid_dbm[i] && dbm >= valid_dbm[i - 1])
    {
      power = valid_dbm[i - 1];
    }
  }'

Ignore me 👍 

Thanks
Kev
